marvel/urls.py
from django.urls import path
from . import views

app_name = 'twitter'
urlpatterns = [
    path('', views.index, name='index'),
    path('api/marvel/characters', views.characters, name="characters"),
    path('api/marvel/character/search', views.characterSearch, name="characterSearch"),
    path('api/marvel/comics', views.comics, name="comics"),
    path('api/marvel/comics/search', views.comicsSearch, name="comicsSearch"),
]

ues_demo/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    # Marvel is default app
    path('', include('marvel.urls')),
]

marvel/models.py
from django.db import models

class Character(models.Model):
    id = models.UUIDField(primary_key=True)
    name = models.CharField(max_length=500)
    thumbnail = models.CharField(max_length=10000)

    def json(self):
        return {
            'id': self.id,
            'name': self.name,
            'thumbnail': self.thumbnail,
        }

    def __str__(self):
        return self.name

class Comic(models.Model):
    name = models.CharField(max_length=500)
    character = models.ForeignKey(
        Character,
        on_delete=models.CASCADE
    )

    def json(self):
        return {
            'name': self.name,
            'character': self.character,
        }

    def __str__(self):
        return self.name

marvel/views.py
from django.http import HttpResponse, JsonResponse
from django.template import loader

from marvel.models import Character, Comic

app_name = 'marvel'
def index(request):
    query = request.GET.get('q', '')
    searchCharacters = []
    if query != '':
        searchCharacters = Character.objects.filter(name__contains=query).select_related()
    template = loader.get_template('marvel/index.html')
    context = {
         # All characters and Comics
        'allCharacters': Character.objects.select_related(),
        'searchCharacters': searchCharacters,
        'query': query,
    }
    return HttpResponse(template.render(context, request))

def characters(request):
    return JsonResponse(list(Character.objects.values()), safe=False)

def characterSearch(request):
    query = request.GET.get('q', '')
    if (query == ''): return JsonResponse([])
    result = []
    characters = Character.objects.filter(name__contains=query)
    for character in characters:
        characterJson = character.json()
        characterJson['comics'] = list(Comic.objects.filter(character=character).values())
        result.append(characterJson)
    return JsonResponse(result, safe=False)

def comics(request):
    return JsonResponse(list(Comic.objects.values()), safe=False)

def comicsSearch(request):
    query = request.GET.get('q', '')
    if (query == ''): return JsonResponse([])
    result = []
    comics = Comic.objects.filter(name__contains=query)
    for comic in comics:
        comicJson = comic.json()
        comicJson['character'] = comicJson['character'].json()
        result.append(comicJson)
    return JsonResponse(result, safe=False)

marvel/templates/marvel/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Character Name Search</title>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        <style>
            #characters-container {
                max-width: 25rem;
                height: 100%;
                overflow: hidden;
            }

            .characters {
                display: flex;
                flex-direction: column;
                justify-content: center;
                overflow: auto;
                margin-top: 2rem;
            }

            #search-container {
                max-width: 25rem;
                height: 100%;
            }
        </style>
    </head>
    <body>
        <div class="container-fluid px-5 pt-5">
          <div class="row">

            <div class="col-lg col-md-6">
                {% comment %} Search Characters {% endcomment %}
                <div id="characters-container">
                    <h3>Search Character's Name:</h3>
                    <form action="" method="GET">
                        <div class="input-group">
                            <input class="form-control" name="q" value="{{ query }}">
                            <div class="input-group-append">
                                <button class="btn btn-primary"><i class="fas fa-search"></i></button>
                            </div>
                        </div>
                    </form>
                    {% if searchCharacters %}
                        <div class="characters">
                        {% for character in searchCharacters %}
                            <div class="card mb-5">
                                <img class="card-img-top" src="{{ character.thumbnail }}">
                                <div class="card-body">
                                    <h5 class="card-title">{{ character.name }}</h5>
                                    <ul class="list-group list-group-flush">
                                        {% if character.comic_set.count > 0 %}
                                            <li class="list-group-item"><h5>Comic appearances:</h5></li>
                                            {% for comic in character.comic_set.all %}
                                                <li class="list-group-item">{{ comic.name }}</li>
                                            {% endfor %}
                                        {% else %}
                                            <li class="list-group-item"><p>No comic appearances.</p></li>
                                        {% endif %}
                                    </ul>
                                </div>
                            </div>
                        {% endfor %}
                        </div>
                    {% else %}
                        <p>No characters where found.</p>
                    {% endif %}
                </div>
            </div>

        </div>
        <footer><a href=\"http://marvel.com\">Data provided by Marvel. © 2020 MARVEL</a></footer>
    </body>
</html>